root = "."
testdata_dir = "testdata"

[build]
  bin = "/usr/local/bin/pdc source/main.lua build/Wordhole.pdx"
  cmd = "/usr/bin/true"
  delay = 1000
  include_ext = ["lua"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
